// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rflap_metrics.Models;

namespace rflap_metrics.Migrations.Export
{
    [DbContext(typeof(ExportContext))]
    partial class ExportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Export", b =>
                {
                    b.Property<int>("dataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("downloadPacket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exportID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exportTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("initialState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numAccepting")
                        .HasColumnType("int");

                    b.Property<int>("numStates")
                        .HasColumnType("int");

                    b.Property<int>("numTransitions")
                        .HasColumnType("int");

                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dataID");

                    b.ToTable("Export");
                });
#pragma warning restore 612, 618
        }
    }
}
