// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rflap_metrics.Models;

namespace rflap_metrics.Migrations.TestResult
{
    [DbContext(typeof(TestResultContext))]
    partial class TestResultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestResult", b =>
                {
                    b.Property<string>("dataID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("callbackHint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("callbackPacket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("callbackTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numCorrect")
                        .HasColumnType("int");

                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("testStringsCorrect")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dataID");

                    b.ToTable("TestResult");
                });
#pragma warning restore 612, 618
        }
    }
}
